"""empty message

Revision ID: 309bba9c06cd
Revises: None
Create Date: 2014-06-23 13:16:20.248784

"""

# revision identifiers, used by Alembic.
revision = '309bba9c06cd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Items')
    op.drop_table('Mages')
    ### end Alembic commands ###
